/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { academicSessionsDelete } from "../../funcs/academicSessionsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteAcademicSessionRequest$inboundSchema,
};

export const tool$academicSessionsDelete: ToolDefinition<typeof args> = {
  name: "academic-sessions-delete",
  description: `Delete an Academic Session

Perform a soft delete on a specific Academic Session on the service provider. This operation changes the status of the Academic Session to 'tobedeleted'.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await academicSessionsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
