/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { academicSessionsCreate } from "../../funcs/academicSessionsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostAcademicSessionRequest$inboundSchema.optional(),
};

export const tool$academicSessionsCreate: ToolDefinition<typeof args> = {
  name: "academic-sessions-create",
  description: `Create an academic session

Creates a new academic session`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await academicSessionsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
