/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { academicSessionsManagementPostAcademicSession } from "../../funcs/academicSessionsManagementPostAcademicSession.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostAcademicSessionRequest$inboundSchema.optional(),
};

export const tool$academicSessionsManagementPostAcademicSession: ToolDefinition<
  typeof args
> = {
  name: "academic-sessions-management-post-academic-session",
  description: `Create an Academic Session

To create a new academic session. The responding system must return the set of sourcedIds that have been allocated to the newly created academicSession record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await academicSessionsManagementPostAcademicSession(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
