/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { academicSessionsGetAll } from "../../funcs/academicSessionsGetAll.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$academicSessionsGetAll: ToolDefinition = {
  name: "academic-sessions-get-all",
  description: `Get all academic sessions

Returns a collection of academic sessions`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await academicSessionsGetAll(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
