/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentResultsGetAll } from "../../funcs/assessmentResultsGetAll.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllAssessmentResultsRequest$inboundSchema,
};

export const tool$assessmentResultsGetAll: ToolDefinition<typeof args> = {
  name: "assessment-results-get-all",
  description:
    `The REST read request message for the getAllAssessmentResults() API call.

Get all of the Assessment Results on the service provider.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assessmentResultsGetAll(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
