/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentResultsDelete } from "../../funcs/assessmentResultsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteAssessmentResultRequest$inboundSchema,
};

export const tool$assessmentResultsDelete: ToolDefinition<typeof args> = {
  name: "assessment-results-delete",
  description:
    `The REST delete request message for the deleteAssessmentResult() API call.

Perform a soft delete on a specific Assessment Result on the service provider. This operation changes the status of the Assessment Result to 'tobedeleted'.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assessmentResultsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
