/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentResultsUpdate } from "../../funcs/assessmentResultsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateAssessmentResultRequest$inboundSchema,
};

export const tool$assessmentResultsUpdate: ToolDefinition<typeof args> = {
  name: "assessment-results-update",
  description: `Update an Assessment Result

To update an existing Assessment Result. The sourcedId for the record to be updated is supplied by the requesting system.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assessmentResultsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
