/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentResultsGet } from "../../funcs/assessmentResultsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAssessmentResultRequest$inboundSchema,
};

export const tool$assessmentResultsGet: ToolDefinition<typeof args> = {
  name: "assessment-results-get",
  description: `Get an Assessment Result

Get a specific Assessment Result on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Assessment result not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assessmentResultsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
