/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentResultsManagementCreateAssessmentResult } from "../../funcs/assessmentResultsManagementCreateAssessmentResult.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateAssessmentResultRequest$inboundSchema,
};

export const tool$assessmentResultsManagementCreateAssessmentResult:
  ToolDefinition<typeof args> = {
    name: "assessment-results-management-create-assessment-result",
    description: `Create an Assessment Result

To create an Assessment Result. The responding system must return the set of sourcedIds that have been allocated to the newly created assessmentResult record. An Assessment Line Item sourcedId and Student sourcedId MUST be provided when creating an assessmentResult.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await assessmentResultsManagementCreateAssessmentResult(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
