/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesGetAll } from "../../funcs/categoriesGetAll.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$categoriesGetAll: ToolDefinition = {
  name: "categories-get-all",
  description:
    `The REST read request message for the getAllCategories() API call.

Get all of the lineItem categories on the service provider.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await categoriesGetAll(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
