/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesDelete } from "../../funcs/categoriesDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteCategoryRequest$inboundSchema,
};

export const tool$categoriesDelete: ToolDefinition<typeof args> = {
  name: "categories-delete",
  description:
    `The REST delete request message for the deleteCategory() API call.

Perform a soft delete on a specific Category on the service provider. This operation changes the status of the Category to 'tobedeleted'.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await categoriesDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
