/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesManagementDeleteCategory } from "../../funcs/categoriesManagementDeleteCategory.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteCategoryRequest$inboundSchema,
};

export const tool$categoriesManagementDeleteCategory: ToolDefinition<
  typeof args
> = {
  name: "categories-management-delete-category",
  description: `Delete a Category

Perform a soft delete on a specific Category on the service provider. This operation changes the status of the Category to 'tobedeleted'.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await categoriesManagementDeleteCategory(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
