/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesGetAll } from "../../funcs/categoriesGetAll.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllCategoriesRequest$inboundSchema,
};

export const tool$categoriesGetAll: ToolDefinition<typeof args> = {
  name: "categories-get-all",
  description: `Get all Categories

Get all of the Line Item Categories on the service provider.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await categoriesGetAll(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
