/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesGet } from "../../funcs/categoriesGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCategoryRequest$inboundSchema,
};

export const tool$categoriesGet: ToolDefinition<typeof args> = {
  name: "categories-get",
  description: `The REST read request message for the getCategory() API call.

Get a specific category on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Category not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await categoriesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
