/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesAddStudent } from "../../funcs/classesAddStudent.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AddStudentToClassRequest$inboundSchema,
};

export const tool$classesAddStudent: ToolDefinition<typeof args> = {
  name: "classes-add-student",
  description: `Add a student to a Class

Enrolls a student in a specific Class. The responding system must return the set of sourcedIds that have been allocated to the newly created enrollment record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesAddStudent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
