/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesResultsGetForLineItem } from "../../funcs/classesResultsGetForLineItem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResultsForLineItemForClassRequest$inboundSchema,
};

export const tool$classesResultsGetForLineItem: ToolDefinition<typeof args> = {
  name: "classes-results-get-for-line-item",
  description: `Get Results for a Line Item for a Class

Get the set of results on the service provider for a specific lineItem and for a specific class. If the corresponding record cannot be located, the api will return a 404 error code and message 'Class or line item not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesResultsGetForLineItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
