/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesManagementGetClass } from "../../funcs/classesManagementGetClass.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetClassRequest$inboundSchema,
};

export const tool$classesManagementGetClass: ToolDefinition<typeof args> = {
  name: "classes-management-get-class",
  description: `Get a specific class

Get a specific Class on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Class not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesManagementGetClass(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
