/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesGetCategories } from "../../funcs/classesGetCategories.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCategoriesForClassRequest$inboundSchema,
};

export const tool$classesGetCategories: ToolDefinition<typeof args> = {
  name: "classes-get-categories",
  description: `Get categories for a class

Returns a collection of categories associated with a specific class.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesGetCategories(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
