/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesGetTeachers } from "../../funcs/classesGetTeachers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTeachersForClassInSchoolRequest$inboundSchema,
};

export const tool$classesGetTeachers: ToolDefinition<typeof args> = {
  name: "classes-get-teachers",
  description: `Get teachers for a specific class in a school

Returns a collection of teachers assigned to a specific class within a school`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesGetTeachers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
