/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesGetCategories } from "../../funcs/classesGetCategories.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCategoriesForClassRequest$inboundSchema,
};

export const tool$classesGetCategories: ToolDefinition<typeof args> = {
  name: "classes-get-categories",
  description: `Get Categories for a Class

Get the set of categories on the service provider for a specific class. If the corresponding record cannot be located, the api will return a 404 error code and message 'Class not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesGetCategories(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
