/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { classesListResources } from "../../funcs/classesListResources.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResourcesForClassRequest$inboundSchema,
};

export const tool$classesListResources: ToolDefinition<typeof args> = {
  name: "classes-list-resources",
  description: `Get resources for a class

To get the collection of resources available to a specific class. If the corresponding record cannot be located, the api will return a 404 error code and message 'Class not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await classesListResources(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
