/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesCreateComponentResource } from "../../funcs/coursesCreateComponentResource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateComponentResourceRequest$inboundSchema.optional(),
};

export const tool$coursesCreateComponentResource: ToolDefinition<typeof args> =
  {
    name: "courses-create-component-resource",
    description: `Create Component Resource

Used when creating a new component resource`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await coursesCreateComponentResource(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
