/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesUpdateComponentResource } from "../../funcs/coursesUpdateComponentResource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutComponentResourceRequest$inboundSchema,
};

export const tool$coursesUpdateComponentResource: ToolDefinition<typeof args> =
  {
    name: "courses-update-component-resource",
    description: `Update a Component Resource

To update an existing Component Resource. The sourcedId for the record to be updated is supplied by the requesting system.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await coursesUpdateComponentResource(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
