/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesDeleteComponentResource } from "../../funcs/coursesDeleteComponentResource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteComponentResourceRequest$inboundSchema,
};

export const tool$coursesDeleteComponentResource: ToolDefinition<typeof args> =
  {
    name: "courses-delete-component-resource",
    description: `Delete a Component Resource

Perform a soft delete on a specific Component Resource on the service provider. The operation changes the status of the Component Resource to 'tobedeleted'.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await coursesDeleteComponentResource(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
