/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { courseComponentsManagementGetAllCourseComponents } from "../../funcs/courseComponentsManagementGetAllCourseComponents.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllCourseComponentsRequest$inboundSchema,
};

export const tool$courseComponentsManagementGetAllCourseComponents:
  ToolDefinition<typeof args> = {
    name: "course-components-management-get-all-course-components",
    description: `Get all Course Components

To get all Course Components on the service provider.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await courseComponentsManagementGetAllCourseComponents(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
