/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesUpdate } from "../../funcs/coursesUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutCourseRequest$inboundSchema,
};

export const tool$coursesUpdate: ToolDefinition<typeof args> = {
  name: "courses-update",
  description: `Update Course

Updates an existing course`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await coursesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
