/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesManagementCreateCourse } from "../../funcs/coursesManagementCreateCourse.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCourseRequest$inboundSchema.optional(),
};

export const tool$coursesManagementCreateCourse: ToolDefinition<typeof args> = {
  name: "courses-management-create-course",
  description: `Create a Course

To create a new Course. The responding system must return the set of sourcedIds that have been allocated to the newly created course record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await coursesManagementCreateCourse(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
