/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesManagementCreateCourseComponent } from "../../funcs/coursesManagementCreateCourseComponent.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCourseComponentRequest$inboundSchema.optional(),
};

export const tool$coursesManagementCreateCourseComponent: ToolDefinition<
  typeof args
> = {
  name: "courses-management-create-course-component",
  description: `Create Course Component

Used when creating a new course component or module`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await coursesManagementCreateCourseComponent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
