/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesGetComponent } from "../../funcs/coursesGetComponent.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCourseComponentRequest$inboundSchema,
};

export const tool$coursesGetComponent: ToolDefinition<typeof args> = {
  name: "courses-get-component",
  description: `Get a specific Course Component

Get a specific Course Component on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Course Component not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await coursesGetComponent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
