/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coursesManagementPutCourse } from "../../funcs/coursesManagementPutCourse.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutCourseRequest$inboundSchema,
};

export const tool$coursesManagementPutCourse: ToolDefinition<typeof args> = {
  name: "courses-management-put-course",
  description: `Update a Course

To update an existing Course. The sourcedId for the record to be updated is supplied by the requesting system.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await coursesManagementPutCourse(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
