/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { demographicsManagementGetDemographics } from "../../funcs/demographicsManagementGetDemographics.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetDemographicsRequest$inboundSchema,
};

export const tool$demographicsManagementGetDemographics: ToolDefinition<
  typeof args
> = {
  name: "demographics-management-get-demographics",
  description: `Get a specific Demographic record

Get a specific Demographic record on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Demographics record not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await demographicsManagementGetDemographics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
