/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { enrollmentsGetForClass } from "../../funcs/enrollmentsGetForClass.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetEnrollmentsForClassInSchoolRequest$inboundSchema,
};

export const tool$enrollmentsGetForClass: ToolDefinition<typeof args> = {
  name: "enrollments-get-for-class",
  description: `Get enrollments for a specific class in a school

Returns a collection of enrollments for a specific class within a school`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await enrollmentsGetForClass(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
