/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { enrollmentsUpdate } from "../../funcs/enrollmentsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateEnrollmentRequest$inboundSchema,
};

export const tool$enrollmentsUpdate: ToolDefinition<typeof args> = {
  name: "enrollments-update",
  description: `Update an Enrollment

To update an existing Enrollment. The sourcedId for the record to be updated is supplied by the requesting system.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await enrollmentsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
