/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gradingPeriodsManagementCreateGradingPeriodForTerm } from "../../funcs/gradingPeriodsManagementCreateGradingPeriodForTerm.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateGradingPeriodForTermRequest$inboundSchema,
};

export const tool$gradingPeriodsManagementCreateGradingPeriodForTerm:
  ToolDefinition<typeof args> = {
    name: "grading-periods-management-create-grading-period-for-term",
    description: `Create a new Grading Period for a Term

To create a new Grading Period for a Term. A Grading Period is a type of Academic Session. The responding system must return the set of sourcedIds that have been allocated to the newly created academicSession record.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await gradingPeriodsManagementCreateGradingPeriodForTerm(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
