/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gradingPeriodsManagementGetGradingPeriod } from "../../funcs/gradingPeriodsManagementGetGradingPeriod.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetGradingPeriodRequest$inboundSchema,
};

export const tool$gradingPeriodsManagementGetGradingPeriod: ToolDefinition<
  typeof args
> = {
  name: "grading-periods-management-get-grading-period",
  description: `Get a specific Grading Period

Get a specific Grading Period on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Grading period not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await gradingPeriodsManagementGetGradingPeriod(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
