/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lineItemsUpdate } from "../../funcs/lineItemsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateLineItemRequest$inboundSchema,
};

export const tool$lineItemsUpdate: ToolDefinition<typeof args> = {
  name: "line-items-update",
  description: `Update an existing line item

Updates an existing line item with the provided information.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await lineItemsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
