/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lineItemsDelete } from "../../funcs/lineItemsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteLineItemRequest$inboundSchema,
};

export const tool$lineItemsDelete: ToolDefinition<typeof args> = {
  name: "line-items-delete",
  description: `Delete a Line Item

Perform a soft delete on a specific Line Item on the service provider. This operation changes the status of the LineItem to 'tobedeleted'.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await lineItemsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
