/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lineItemsGet } from "../../funcs/lineItemsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetLineItemRequest$inboundSchema,
};

export const tool$lineItemsGet: ToolDefinition<typeof args> = {
  name: "line-items-get",
  description: `Get a Line Item

Get a specific Line Item on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Line item not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await lineItemsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
