/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsManagementCreateOrg } from "../../funcs/organizationsManagementCreateOrg.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateOrgRequest$inboundSchema.optional(),
};

export const tool$organizationsManagementCreateOrg: ToolDefinition<
  typeof args
> = {
  name: "organizations-management-create-org",
  description: `Create an Organization

To create a new Organization. The responding system must return the set of sourcedIds that have been allocated to the newly created org record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationsManagementCreateOrg(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
