/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesCoursesManagementAssignResourceToCourse } from "../../funcs/resourcesCoursesManagementAssignResourceToCourse.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AssignResourceToCourseRequest$inboundSchema,
};

export const tool$resourcesCoursesManagementAssignResourceToCourse:
  ToolDefinition<typeof args> = {
    name: "resources-courses-management-assign-resource-to-course",
    description: `Assign a resource to a course

To assign an existing resource to the specified course. The course sourcedId is supplied by the requesting system. If the corresponding record cannot be located, the api will return a 404 error code and message 'Course or resource not found.'`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await resourcesCoursesManagementAssignResourceToCourse(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
