/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesGetAll } from "../../funcs/resourcesGetAll.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllResourcesRequest$inboundSchema,
};

export const tool$resourcesGetAll: ToolDefinition<typeof args> = {
  name: "resources-get-all",
  description: `Get all Resources

To get a collection of resources that exist on the service provider.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resourcesGetAll(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
