/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesCreate } from "../../funcs/resourcesCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateResourceRequest$inboundSchema,
};

export const tool$resourcesCreate: ToolDefinition<typeof args> = {
  name: "resources-create",
  description: `Create a new Resource

To create a new resource. The responding system must return the set of sourcedIds that have been allocated to the newly created resource record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resourcesCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
