/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesGetAll } from "../../funcs/resourcesGetAll.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$resourcesGetAll: ToolDefinition = {
  name: "resources-get-all",
  description: `Get all resources

Returns a collection of all resources.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await resourcesGetAll(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
