/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resultsDelete } from "../../funcs/resultsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteResultRequest$inboundSchema,
};

export const tool$resultsDelete: ToolDefinition<typeof args> = {
  name: "results-delete",
  description: `Delete a result

Deletes a result with the specified sourcedId.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resultsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
