/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resultsUpdate } from "../../funcs/resultsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateResultRequest$inboundSchema,
};

export const tool$resultsUpdate: ToolDefinition<typeof args> = {
  name: "results-update",
  description: `Update an existing result

Updates an existing result with the provided information.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await resultsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
