/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schoolsGetStudents } from "../../funcs/schoolsGetStudents.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetStudentsForSchoolRequest$inboundSchema,
};

export const tool$schoolsGetStudents: ToolDefinition<typeof args> = {
  name: "schools-get-students",
  description: `Get all students for a school

Returns a collection of students enrolled in a specific school`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await schoolsGetStudents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
