/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schoolsScoreScalesGet } from "../../funcs/schoolsScoreScalesGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetScoreScalesForSchoolRequest$inboundSchema,
};

export const tool$schoolsScoreScalesGet: ToolDefinition<typeof args> = {
  name: "schools-score-scales-get",
  description: `Get score scales for a school

Returns a collection of score scales associated with the specified school.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await schoolsScoreScalesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
