/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scoreScalesUpdate } from "../../funcs/scoreScalesUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateScoreScaleRequest$inboundSchema,
};

export const tool$scoreScalesUpdate: ToolDefinition<typeof args> = {
  name: "score-scales-update",
  description: `Update a Score Scale

To update an existing scoreScale. The sourcedId for the record to be updated is supplied by the requesting system.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scoreScalesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
