/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scoreScalesGet } from "../../funcs/scoreScalesGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetScoreScaleRequest$inboundSchema,
};

export const tool$scoreScalesGet: ToolDefinition<typeof args> = {
  name: "score-scales-get",
  description: `Get a specific score scale

Returns a specific score scale by sourcedId.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scoreScalesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
