/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { studentsGet } from "../../funcs/studentsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetStudentRequest$inboundSchema,
};

export const tool$studentsGet: ToolDefinition<typeof args> = {
  name: "students-get",
  description: `Get a specific student

Returns a specific student by sourcedId.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await studentsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
