/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teachersManagementGetTeacher } from "../../funcs/teachersManagementGetTeacher.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTeacherRequest$inboundSchema,
};

export const tool$teachersManagementGetTeacher: ToolDefinition<typeof args> = {
  name: "teachers-management-get-teacher",
  description: `Get a specific Teacher

To get a specific Teacher on the service provider. If the corresponding record cannot be located, the api will return a 404 error code and message 'Teacher not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await teachersManagementGetTeacher(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
