/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teachersManagementAddTeacherToClass } from "../../funcs/teachersManagementAddTeacherToClass.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AddTeacherToClassRequest$inboundSchema,
};

export const tool$teachersManagementAddTeacherToClass: ToolDefinition<
  typeof args
> = {
  name: "teachers-management-add-teacher-to-class",
  description: `Add a teacher to a Class

Enrolls a teacher to a specific Class. The responding system must return the set of sourcedIds that have been allocated to the newly created enrollment record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await teachersManagementAddTeacherToClass(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
