/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teachersManagementGetTeachersForClass } from "../../funcs/teachersManagementGetTeachersForClass.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTeachersForClassRequest$inboundSchema,
};

export const tool$teachersManagementGetTeachersForClass: ToolDefinition<
  typeof args
> = {
  name: "teachers-management-get-teachers-for-class",
  description: `Get teachers for a Class

To get all teachers assigned to a specific Class. If the corresponding record cannot be located, the api will return a 404 error code and message 'Class not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await teachersManagementGetTeachersForClass(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
