/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { termsList } from "../../funcs/termsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllTermsRequest$inboundSchema,
};

export const tool$termsList: ToolDefinition<typeof args> = {
  name: "terms-list",
  description: `Get all Terms

To get all Terms on the service provider.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await termsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
