/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { termsList } from "../../funcs/termsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$termsList: ToolDefinition = {
  name: "terms-list",
  description: `Get all terms

Returns a collection of all terms.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await termsList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
