/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersAssignResource } from "../../funcs/usersAssignResource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AssignResourceToUserRequest$inboundSchema,
};

export const tool$usersAssignResource: ToolDefinition<typeof args> = {
  name: "users-assign-resource",
  description: `Assign a resource to a user

To assign an existing resource to the specified user. If the corresponding record cannot be located, the api will return a 404 error code and message 'User or resource not found.'`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersAssignResource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
