/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersManagementGetClassesForUser } from "../../funcs/usersManagementGetClassesForUser.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetClassesForUserRequest$inboundSchema,
};

export const tool$usersManagementGetClassesForUser: ToolDefinition<
  typeof args
> = {
  name: "users-management-get-classes-for-user",
  description: `Get Classes for a User

To get the set of Classes a User is enrolled in.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersManagementGetClassesForUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
