/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetResources } from "../../funcs/usersGetResources.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetResourcesForUserRequest$inboundSchema,
};

export const tool$usersGetResources: ToolDefinition<typeof args> = {
  name: "users-get-resources",
  description: `Get resources for a user

Returns a collection of resources associated with the user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersGetResources(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
