/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersManagementUpdateUser } from "../../funcs/usersManagementUpdateUser.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateUserRequest$inboundSchema,
};

export const tool$usersManagementUpdateUser: ToolDefinition<typeof args> = {
  name: "users-management-update-user",
  description: `Update an existing User

To update an existing User on the service provider. The sourcedId for the record to be updated is supplied by the requesting system.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersManagementUpdateUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
