/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { courseResourcesDelete } from "../funcs/courseResourcesDelete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CourseResources extends ClientSDK {
  /**
   * Remove a resource from a course
   *
   * @remarks
   * Removes the specified resource from the course.
   */
  async delete(
    request: operations.RemoveResourceFromCourseRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(courseResourcesDelete(
      this,
      request,
      options,
    ));
  }
}
