/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schoolsScoreScalesGet } from "../funcs/schoolsScoreScalesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SchoolsScoreScales extends ClientSDK {
  /**
   * Get score scales for a school
   *
   * @remarks
   * Returns a collection of score scales associated with the specified school.
   */
  async get(
    request: operations.GetScoreScalesForSchoolRequest,
    options?: RequestOptions,
  ): Promise<operations.GetScoreScalesForSchoolResponse> {
    return unwrapAsync(schoolsScoreScalesGet(
      this,
      request,
      options,
    ));
  }
}
