/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { studentsClassesGet } from "../funcs/studentsClassesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class StudentsClasses extends ClientSDK {
  /**
   * Get classes for a student
   *
   * @remarks
   * Returns a collection of classes that the student is enrolled in.
   */
  async get(
    request: operations.GetClassesForStudentRequest,
    options?: RequestOptions,
  ): Promise<operations.GetClassesForStudentResponse> {
    return unwrapAsync(studentsClassesGet(
      this,
      request,
      options,
    ));
  }
}
