/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userResourcesRemove } from "../funcs/userResourcesRemove.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserResources extends ClientSDK {
  /**
   * Remove a resource from a user
   *
   * @remarks
   * Removes the specified resource from the user.
   */
  async remove(
    request: operations.RemoveResourceFromUserRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(userResourcesRemove(
      this,
      request,
      options,
    ));
  }
}
