/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersAssignResource } from "../funcs/usersAssignResource.js";
import { usersCreate } from "../funcs/usersCreate.js";
import { usersDelete } from "../funcs/usersDelete.js";
import { usersGet } from "../funcs/usersGet.js";
import { usersGetAll } from "../funcs/usersGetAll.js";
import { usersGetClasses } from "../funcs/usersGetClasses.js";
import { usersGetResources } from "../funcs/usersGetResources.js";
import { usersUpdate } from "../funcs/usersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Users extends ClientSDK {
  /**
   * Get resources for a user
   *
   * @remarks
   * To get the collection of resources available to a specific user. If the corresponding record cannot be located, the api will return a 404 error code and message 'User not found.'
   */
  async getResources(
    request: operations.GetResourcesForUserRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetResourcesForUserResponse, { offset: number }>
  > {
    return unwrapResultIterator(usersGetResources(
      this,
      request,
      options,
    ));
  }

  /**
   * Assign a resource to a user
   *
   * @remarks
   * To assign an existing resource to the specified user. If the corresponding record cannot be located, the api will return a 404 error code and message 'User or resource not found.'
   */
  async assignResource(
    request: operations.AssignResourceToUserRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(usersAssignResource(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all Users
   *
   * @remarks
   * To get all Users on the service provider.
   */
  async getAll(
    request: operations.GetAllUsersRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetAllUsersResponse, { offset: number }>> {
    return unwrapResultIterator(usersGetAll(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new User
   *
   * @remarks
   * To create a new User on the service provider. The responding system must return the set of sourcedIds that have been allocated to the newly created user record.
   */
  async create(
    request: operations.CreateUserRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateUserResponse> {
    return unwrapAsync(usersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific User
   *
   * @remarks
   * To get a specific User on the service provider.
   */
  async get(
    request: operations.GetUserRequest,
    options?: RequestOptions,
  ): Promise<operations.GetUserResponse> {
    return unwrapAsync(usersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing User
   *
   * @remarks
   * To update an existing User on the service provider. The sourcedId for the record to be updated is supplied by the requesting system.
   */
  async update(
    request: operations.UpdateUserRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateUserResponse> {
    return unwrapAsync(usersUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a User
   *
   * @remarks
   * Perform a soft delete on a specific User on the service provider. This operation changes the status of the User to 'tobedeleted'.
   */
  async delete(
    request: operations.DeleteUserRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Classes for a User
   *
   * @remarks
   * To get the set of Classes a User is enrolled in.
   */
  async getClasses(
    request: operations.GetClassesForUserRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetClassesForUserResponse, { offset: number }>
  > {
    return unwrapResultIterator(usersGetClasses(
      this,
      request,
      options,
    ));
  }
}
