/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteCategoryRequest = {
  /**
   * The sourcedId of the category to delete
   */
  sourcedId: string;
};

/** @internal */
export const DeleteCategoryRequest$inboundSchema: z.ZodType<
  DeleteCategoryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});

/** @internal */
export type DeleteCategoryRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const DeleteCategoryRequest$outboundSchema: z.ZodType<
  DeleteCategoryRequest$Outbound,
  z.ZodTypeDef,
  DeleteCategoryRequest
> = z.object({
  sourcedId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCategoryRequest$ {
  /** @deprecated use `DeleteCategoryRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteCategoryRequest$inboundSchema;
  /** @deprecated use `DeleteCategoryRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteCategoryRequest$outboundSchema;
  /** @deprecated use `DeleteCategoryRequest$Outbound` instead. */
  export type Outbound = DeleteCategoryRequest$Outbound;
}

export function deleteCategoryRequestToJSON(
  deleteCategoryRequest: DeleteCategoryRequest,
): string {
  return JSON.stringify(
    DeleteCategoryRequest$outboundSchema.parse(deleteCategoryRequest),
  );
}

export function deleteCategoryRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCategoryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCategoryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCategoryRequest' from JSON`,
  );
}
