/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAssessmentLineItemRequest = {
  /**
   * The sourcedId of the assessment line item
   */
  sourcedId: string;
};

/**
 * Successful response with the assessment line item
 */
export type GetAssessmentLineItemResponse = {
  /**
   * Represents an assessment line item.
   */
  assessmentLineItem: components.AssessmentLineItem;
};

/** @internal */
export const GetAssessmentLineItemRequest$inboundSchema: z.ZodType<
  GetAssessmentLineItemRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});

/** @internal */
export type GetAssessmentLineItemRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetAssessmentLineItemRequest$outboundSchema: z.ZodType<
  GetAssessmentLineItemRequest$Outbound,
  z.ZodTypeDef,
  GetAssessmentLineItemRequest
> = z.object({
  sourcedId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAssessmentLineItemRequest$ {
  /** @deprecated use `GetAssessmentLineItemRequest$inboundSchema` instead. */
  export const inboundSchema = GetAssessmentLineItemRequest$inboundSchema;
  /** @deprecated use `GetAssessmentLineItemRequest$outboundSchema` instead. */
  export const outboundSchema = GetAssessmentLineItemRequest$outboundSchema;
  /** @deprecated use `GetAssessmentLineItemRequest$Outbound` instead. */
  export type Outbound = GetAssessmentLineItemRequest$Outbound;
}

export function getAssessmentLineItemRequestToJSON(
  getAssessmentLineItemRequest: GetAssessmentLineItemRequest,
): string {
  return JSON.stringify(
    GetAssessmentLineItemRequest$outboundSchema.parse(
      getAssessmentLineItemRequest,
    ),
  );
}

export function getAssessmentLineItemRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAssessmentLineItemRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAssessmentLineItemRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssessmentLineItemRequest' from JSON`,
  );
}

/** @internal */
export const GetAssessmentLineItemResponse$inboundSchema: z.ZodType<
  GetAssessmentLineItemResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  assessmentLineItem: components.AssessmentLineItem$inboundSchema,
});

/** @internal */
export type GetAssessmentLineItemResponse$Outbound = {
  assessmentLineItem: components.AssessmentLineItem$Outbound;
};

/** @internal */
export const GetAssessmentLineItemResponse$outboundSchema: z.ZodType<
  GetAssessmentLineItemResponse$Outbound,
  z.ZodTypeDef,
  GetAssessmentLineItemResponse
> = z.object({
  assessmentLineItem: components.AssessmentLineItem$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAssessmentLineItemResponse$ {
  /** @deprecated use `GetAssessmentLineItemResponse$inboundSchema` instead. */
  export const inboundSchema = GetAssessmentLineItemResponse$inboundSchema;
  /** @deprecated use `GetAssessmentLineItemResponse$outboundSchema` instead. */
  export const outboundSchema = GetAssessmentLineItemResponse$outboundSchema;
  /** @deprecated use `GetAssessmentLineItemResponse$Outbound` instead. */
  export type Outbound = GetAssessmentLineItemResponse$Outbound;
}

export function getAssessmentLineItemResponseToJSON(
  getAssessmentLineItemResponse: GetAssessmentLineItemResponse,
): string {
  return JSON.stringify(
    GetAssessmentLineItemResponse$outboundSchema.parse(
      getAssessmentLineItemResponse,
    ),
  );
}

export function getAssessmentLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAssessmentLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAssessmentLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssessmentLineItemResponse' from JSON`,
  );
}
