/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetClassesForTeacherRequest = {
  /**
   * The sourcedId of the teacher
   */
  teacherSourcedId: string;
};

/**
 * Successful response containing a collection of classes for the teacher
 */
export type GetClassesForTeacherResponse = {
  classes: Array<components.Class>;
};

/** @internal */
export const GetClassesForTeacherRequest$inboundSchema: z.ZodType<
  GetClassesForTeacherRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  teacherSourcedId: z.string(),
});

/** @internal */
export type GetClassesForTeacherRequest$Outbound = {
  teacherSourcedId: string;
};

/** @internal */
export const GetClassesForTeacherRequest$outboundSchema: z.ZodType<
  GetClassesForTeacherRequest$Outbound,
  z.ZodTypeDef,
  GetClassesForTeacherRequest
> = z.object({
  teacherSourcedId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClassesForTeacherRequest$ {
  /** @deprecated use `GetClassesForTeacherRequest$inboundSchema` instead. */
  export const inboundSchema = GetClassesForTeacherRequest$inboundSchema;
  /** @deprecated use `GetClassesForTeacherRequest$outboundSchema` instead. */
  export const outboundSchema = GetClassesForTeacherRequest$outboundSchema;
  /** @deprecated use `GetClassesForTeacherRequest$Outbound` instead. */
  export type Outbound = GetClassesForTeacherRequest$Outbound;
}

export function getClassesForTeacherRequestToJSON(
  getClassesForTeacherRequest: GetClassesForTeacherRequest,
): string {
  return JSON.stringify(
    GetClassesForTeacherRequest$outboundSchema.parse(
      getClassesForTeacherRequest,
    ),
  );
}

export function getClassesForTeacherRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForTeacherRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForTeacherRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForTeacherRequest' from JSON`,
  );
}

/** @internal */
export const GetClassesForTeacherResponse$inboundSchema: z.ZodType<
  GetClassesForTeacherResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  classes: z.array(components.Class$inboundSchema),
});

/** @internal */
export type GetClassesForTeacherResponse$Outbound = {
  classes: Array<components.Class$Outbound>;
};

/** @internal */
export const GetClassesForTeacherResponse$outboundSchema: z.ZodType<
  GetClassesForTeacherResponse$Outbound,
  z.ZodTypeDef,
  GetClassesForTeacherResponse
> = z.object({
  classes: z.array(components.Class$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetClassesForTeacherResponse$ {
  /** @deprecated use `GetClassesForTeacherResponse$inboundSchema` instead. */
  export const inboundSchema = GetClassesForTeacherResponse$inboundSchema;
  /** @deprecated use `GetClassesForTeacherResponse$outboundSchema` instead. */
  export const outboundSchema = GetClassesForTeacherResponse$outboundSchema;
  /** @deprecated use `GetClassesForTeacherResponse$Outbound` instead. */
  export type Outbound = GetClassesForTeacherResponse$Outbound;
}

export function getClassesForTeacherResponseToJSON(
  getClassesForTeacherResponse: GetClassesForTeacherResponse,
): string {
  return JSON.stringify(
    GetClassesForTeacherResponse$outboundSchema.parse(
      getClassesForTeacherResponse,
    ),
  );
}

export function getClassesForTeacherResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForTeacherResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForTeacherResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForTeacherResponse' from JSON`,
  );
}
