/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetResourcesForUserRequest = {
  /**
   * The sourcedId of the user
   */
  userSourcedId: string;
};

/**
 * Successful response containing a collection of resources for the user
 */
export type GetResourcesForUserResponse = {
  resources: Array<components.Resource>;
};

/** @internal */
export const GetResourcesForUserRequest$inboundSchema: z.ZodType<
  GetResourcesForUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userSourcedId: z.string(),
});

/** @internal */
export type GetResourcesForUserRequest$Outbound = {
  userSourcedId: string;
};

/** @internal */
export const GetResourcesForUserRequest$outboundSchema: z.ZodType<
  GetResourcesForUserRequest$Outbound,
  z.ZodTypeDef,
  GetResourcesForUserRequest
> = z.object({
  userSourcedId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetResourcesForUserRequest$ {
  /** @deprecated use `GetResourcesForUserRequest$inboundSchema` instead. */
  export const inboundSchema = GetResourcesForUserRequest$inboundSchema;
  /** @deprecated use `GetResourcesForUserRequest$outboundSchema` instead. */
  export const outboundSchema = GetResourcesForUserRequest$outboundSchema;
  /** @deprecated use `GetResourcesForUserRequest$Outbound` instead. */
  export type Outbound = GetResourcesForUserRequest$Outbound;
}

export function getResourcesForUserRequestToJSON(
  getResourcesForUserRequest: GetResourcesForUserRequest,
): string {
  return JSON.stringify(
    GetResourcesForUserRequest$outboundSchema.parse(getResourcesForUserRequest),
  );
}

export function getResourcesForUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetResourcesForUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourcesForUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourcesForUserRequest' from JSON`,
  );
}

/** @internal */
export const GetResourcesForUserResponse$inboundSchema: z.ZodType<
  GetResourcesForUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resources: z.array(components.Resource$inboundSchema),
});

/** @internal */
export type GetResourcesForUserResponse$Outbound = {
  resources: Array<components.Resource$Outbound>;
};

/** @internal */
export const GetResourcesForUserResponse$outboundSchema: z.ZodType<
  GetResourcesForUserResponse$Outbound,
  z.ZodTypeDef,
  GetResourcesForUserResponse
> = z.object({
  resources: z.array(components.Resource$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetResourcesForUserResponse$ {
  /** @deprecated use `GetResourcesForUserResponse$inboundSchema` instead. */
  export const inboundSchema = GetResourcesForUserResponse$inboundSchema;
  /** @deprecated use `GetResourcesForUserResponse$outboundSchema` instead. */
  export const outboundSchema = GetResourcesForUserResponse$outboundSchema;
  /** @deprecated use `GetResourcesForUserResponse$Outbound` instead. */
  export type Outbound = GetResourcesForUserResponse$Outbound;
}

export function getResourcesForUserResponseToJSON(
  getResourcesForUserResponse: GetResourcesForUserResponse,
): string {
  return JSON.stringify(
    GetResourcesForUserResponse$outboundSchema.parse(
      getResourcesForUserResponse,
    ),
  );
}

export function getResourcesForUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetResourcesForUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourcesForUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourcesForUserResponse' from JSON`,
  );
}
