/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStudentsForClassRequest = {
  /**
   * Class sourcedId
   */
  classSourcedId: string;
};

/** @internal */
export const GetStudentsForClassRequest$inboundSchema: z.ZodType<
  GetStudentsForClassRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  classSourcedId: z.string(),
});

/** @internal */
export type GetStudentsForClassRequest$Outbound = {
  classSourcedId: string;
};

/** @internal */
export const GetStudentsForClassRequest$outboundSchema: z.ZodType<
  GetStudentsForClassRequest$Outbound,
  z.ZodTypeDef,
  GetStudentsForClassRequest
> = z.object({
  classSourcedId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStudentsForClassRequest$ {
  /** @deprecated use `GetStudentsForClassRequest$inboundSchema` instead. */
  export const inboundSchema = GetStudentsForClassRequest$inboundSchema;
  /** @deprecated use `GetStudentsForClassRequest$outboundSchema` instead. */
  export const outboundSchema = GetStudentsForClassRequest$outboundSchema;
  /** @deprecated use `GetStudentsForClassRequest$Outbound` instead. */
  export type Outbound = GetStudentsForClassRequest$Outbound;
}

export function getStudentsForClassRequestToJSON(
  getStudentsForClassRequest: GetStudentsForClassRequest,
): string {
  return JSON.stringify(
    GetStudentsForClassRequest$outboundSchema.parse(getStudentsForClassRequest),
  );
}

export function getStudentsForClassRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetStudentsForClassRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStudentsForClassRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStudentsForClassRequest' from JSON`,
  );
}
