/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostLineItemsForClassRequestBody = {
  /**
   * Represents a line item.
   */
  lineItem: components.LineItem;
};

export type PostLineItemsForClassRequest = {
  /**
   * The sourcedId of the class
   */
  classSourcedId: string;
  requestBody: PostLineItemsForClassRequestBody;
};

export type PostLineItemsForClassSourcedIdPairs = {
  suppliedSourcedId: string;
  allocatedSourcedId: string;
};

/**
 * Line item successfully created
 */
export type PostLineItemsForClassResponse = {
  sourcedIdPairs: PostLineItemsForClassSourcedIdPairs;
};

/** @internal */
export const PostLineItemsForClassRequestBody$inboundSchema: z.ZodType<
  PostLineItemsForClassRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  lineItem: components.LineItem$inboundSchema,
});

/** @internal */
export type PostLineItemsForClassRequestBody$Outbound = {
  lineItem: components.LineItem$Outbound;
};

/** @internal */
export const PostLineItemsForClassRequestBody$outboundSchema: z.ZodType<
  PostLineItemsForClassRequestBody$Outbound,
  z.ZodTypeDef,
  PostLineItemsForClassRequestBody
> = z.object({
  lineItem: components.LineItem$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostLineItemsForClassRequestBody$ {
  /** @deprecated use `PostLineItemsForClassRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostLineItemsForClassRequestBody$inboundSchema;
  /** @deprecated use `PostLineItemsForClassRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostLineItemsForClassRequestBody$outboundSchema;
  /** @deprecated use `PostLineItemsForClassRequestBody$Outbound` instead. */
  export type Outbound = PostLineItemsForClassRequestBody$Outbound;
}

export function postLineItemsForClassRequestBodyToJSON(
  postLineItemsForClassRequestBody: PostLineItemsForClassRequestBody,
): string {
  return JSON.stringify(
    PostLineItemsForClassRequestBody$outboundSchema.parse(
      postLineItemsForClassRequestBody,
    ),
  );
}

export function postLineItemsForClassRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostLineItemsForClassRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostLineItemsForClassRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostLineItemsForClassRequestBody' from JSON`,
  );
}

/** @internal */
export const PostLineItemsForClassRequest$inboundSchema: z.ZodType<
  PostLineItemsForClassRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  classSourcedId: z.string(),
  RequestBody: z.lazy(() => PostLineItemsForClassRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PostLineItemsForClassRequest$Outbound = {
  classSourcedId: string;
  RequestBody: PostLineItemsForClassRequestBody$Outbound;
};

/** @internal */
export const PostLineItemsForClassRequest$outboundSchema: z.ZodType<
  PostLineItemsForClassRequest$Outbound,
  z.ZodTypeDef,
  PostLineItemsForClassRequest
> = z.object({
  classSourcedId: z.string(),
  requestBody: z.lazy(() => PostLineItemsForClassRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostLineItemsForClassRequest$ {
  /** @deprecated use `PostLineItemsForClassRequest$inboundSchema` instead. */
  export const inboundSchema = PostLineItemsForClassRequest$inboundSchema;
  /** @deprecated use `PostLineItemsForClassRequest$outboundSchema` instead. */
  export const outboundSchema = PostLineItemsForClassRequest$outboundSchema;
  /** @deprecated use `PostLineItemsForClassRequest$Outbound` instead. */
  export type Outbound = PostLineItemsForClassRequest$Outbound;
}

export function postLineItemsForClassRequestToJSON(
  postLineItemsForClassRequest: PostLineItemsForClassRequest,
): string {
  return JSON.stringify(
    PostLineItemsForClassRequest$outboundSchema.parse(
      postLineItemsForClassRequest,
    ),
  );
}

export function postLineItemsForClassRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostLineItemsForClassRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostLineItemsForClassRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostLineItemsForClassRequest' from JSON`,
  );
}

/** @internal */
export const PostLineItemsForClassSourcedIdPairs$inboundSchema: z.ZodType<
  PostLineItemsForClassSourcedIdPairs,
  z.ZodTypeDef,
  unknown
> = z.object({
  suppliedSourcedId: z.string(),
  allocatedSourcedId: z.string(),
});

/** @internal */
export type PostLineItemsForClassSourcedIdPairs$Outbound = {
  suppliedSourcedId: string;
  allocatedSourcedId: string;
};

/** @internal */
export const PostLineItemsForClassSourcedIdPairs$outboundSchema: z.ZodType<
  PostLineItemsForClassSourcedIdPairs$Outbound,
  z.ZodTypeDef,
  PostLineItemsForClassSourcedIdPairs
> = z.object({
  suppliedSourcedId: z.string(),
  allocatedSourcedId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostLineItemsForClassSourcedIdPairs$ {
  /** @deprecated use `PostLineItemsForClassSourcedIdPairs$inboundSchema` instead. */
  export const inboundSchema =
    PostLineItemsForClassSourcedIdPairs$inboundSchema;
  /** @deprecated use `PostLineItemsForClassSourcedIdPairs$outboundSchema` instead. */
  export const outboundSchema =
    PostLineItemsForClassSourcedIdPairs$outboundSchema;
  /** @deprecated use `PostLineItemsForClassSourcedIdPairs$Outbound` instead. */
  export type Outbound = PostLineItemsForClassSourcedIdPairs$Outbound;
}

export function postLineItemsForClassSourcedIdPairsToJSON(
  postLineItemsForClassSourcedIdPairs: PostLineItemsForClassSourcedIdPairs,
): string {
  return JSON.stringify(
    PostLineItemsForClassSourcedIdPairs$outboundSchema.parse(
      postLineItemsForClassSourcedIdPairs,
    ),
  );
}

export function postLineItemsForClassSourcedIdPairsFromJSON(
  jsonString: string,
): SafeParseResult<PostLineItemsForClassSourcedIdPairs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostLineItemsForClassSourcedIdPairs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostLineItemsForClassSourcedIdPairs' from JSON`,
  );
}

/** @internal */
export const PostLineItemsForClassResponse$inboundSchema: z.ZodType<
  PostLineItemsForClassResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedIdPairs: z.lazy(() =>
    PostLineItemsForClassSourcedIdPairs$inboundSchema
  ),
});

/** @internal */
export type PostLineItemsForClassResponse$Outbound = {
  sourcedIdPairs: PostLineItemsForClassSourcedIdPairs$Outbound;
};

/** @internal */
export const PostLineItemsForClassResponse$outboundSchema: z.ZodType<
  PostLineItemsForClassResponse$Outbound,
  z.ZodTypeDef,
  PostLineItemsForClassResponse
> = z.object({
  sourcedIdPairs: z.lazy(() =>
    PostLineItemsForClassSourcedIdPairs$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostLineItemsForClassResponse$ {
  /** @deprecated use `PostLineItemsForClassResponse$inboundSchema` instead. */
  export const inboundSchema = PostLineItemsForClassResponse$inboundSchema;
  /** @deprecated use `PostLineItemsForClassResponse$outboundSchema` instead. */
  export const outboundSchema = PostLineItemsForClassResponse$outboundSchema;
  /** @deprecated use `PostLineItemsForClassResponse$Outbound` instead. */
  export type Outbound = PostLineItemsForClassResponse$Outbound;
}

export function postLineItemsForClassResponseToJSON(
  postLineItemsForClassResponse: PostLineItemsForClassResponse,
): string {
  return JSON.stringify(
    PostLineItemsForClassResponse$outboundSchema.parse(
      postLineItemsForClassResponse,
    ),
  );
}

export function postLineItemsForClassResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostLineItemsForClassResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostLineItemsForClassResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostLineItemsForClassResponse' from JSON`,
  );
}
